#ifndef FACTORY_GLOBAL_H
#define FACTORY_GLOBAL_H

#define NULL 0
enum UIC_KIND
{
    UIC_KIND_INVALID = 0,
    UIC_KIND_FUNC_REGION,
    UIC_KIND_SETUP,
    UIC_KIND_SETUPINFO,
    UIC_KIND_PHONE,
    UIC_KIND_APPSTART,
    UIC_KIND_APPS,

    UIC_KIND_END
};

#endif // FACTORY_GLOBAL_H
